import React, { useState } from 'react';
import {
    Card,
    CardContent,
    Typography,
    TextField,
    Button,
    Grid,
    MenuItem,
    Alert,
} from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import { applicationService } from '../../services/applicationService';

interface ApplicationFormData {
    applicationName: string;
    queue: string;
    priority: number;
    applicationType: string;
    memory: number;
    vCores: number;
    maxAppAttempts: number;
    commands: string;
}

const initialFormData: ApplicationFormData = {
    applicationName: '',
    queue: 'default',
    priority: 0,
    applicationType: 'YARN',
    memory: 1024,
    vCores: 1,
    maxAppAttempts: 2,
    commands: '',
};

const ApplicationSubmit: React.FC = () => {
    const [formData, setFormData] = useState<ApplicationFormData>(initialFormData);
    const [submitting, setSubmitting] = useState(false);
    const [success, setSuccess] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: name === 'priority' || name === 'memory' || name === 'vCores' || name === 'maxAppAttempts'
                ? parseInt(value) || 0
                : value,
        }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSubmitting(true);
        setSuccess(null);
        setError(null);

        try {
            const result = await applicationService.submit({
                applicationId: '', // Will be generated by backend
                applicationName: formData.applicationName,
                queue: formData.queue,
                priority: formData.priority,
                applicationType: formData.applicationType,
                memory: formData.memory,
                vCores: formData.vCores,
                maxAppAttempts: formData.maxAppAttempts,
                amContainerSpec: {
                    commands: formData.commands.split('\n').filter(cmd => cmd.trim()),
                },
            });

            setSuccess(`Application submitted successfully! ID: ${result.applicationId}`);
            setFormData(initialFormData);
        } catch (err: any) {
            setError(err.message || 'Failed to submit application');
        } finally {
            setSubmitting(false);
        }
    };

    return (
        <Card>
            <CardContent>
                <Typography variant="h6" gutterBottom>
                    Submit New Application
                </Typography>

                {success && (
                    <Alert severity="success" sx={{ mb: 2 }} onClose={() => setSuccess(null)}>
                        {success}
                    </Alert>
                )}

                {error && (
                    <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>
                        {error}
                    </Alert>
                )}

                <form onSubmit={handleSubmit}>
                    <Grid container spacing={2}>
                        <Grid size={{ xs: 12, md: 6 }}>
                            <TextField
                                fullWidth
                                label="Application Name"
                                name="applicationName"
                                value={formData.applicationName}
                                onChange={handleChange}
                                required
                            />
                        </Grid>
                        <Grid size={{ xs: 12, md: 6 }}>
                            <TextField
                                fullWidth
                                select
                                label="Queue"
                                name="queue"
                                value={formData.queue}
                                onChange={handleChange}
                            >
                                <MenuItem value="default">Default</MenuItem>
                                <MenuItem value="high_priority">High Priority</MenuItem>
                                <MenuItem value="low_priority">Low Priority</MenuItem>
                            </TextField>
                        </Grid>
                        <Grid size={{ xs: 12, md: 4 }}>
                            <TextField
                                fullWidth
                                type="number"
                                label="Priority"
                                name="priority"
                                value={formData.priority}
                                onChange={handleChange}
                                slotProps={{
                                    htmlInput: {
                                        min: 0
                                    }
                                }}
                            />
                        </Grid>
                        <Grid size={{ xs: 12, md: 4 }}>
                            <TextField
                                fullWidth
                                select
                                label="Application Type"
                                name="applicationType"
                                value={formData.applicationType}
                                onChange={handleChange}
                            >
                                <MenuItem value="YARN">YARN</MenuItem>
                                <MenuItem value="MAPREDUCE">MapReduce</MenuItem>
                                <MenuItem value="SPARK">Spark</MenuItem>
                                <MenuItem value="PIG">Pig</MenuItem>
                                <MenuItem value="HIVE">Hive</MenuItem>
                            </TextField>
                        </Grid>
                        <Grid size={{ xs: 12, md: 4 }}>
                            <TextField
                                fullWidth
                                type="number"
                                label="Max Attempts"
                                name="maxAppAttempts"
                                value={formData.maxAppAttempts}
                                onChange={handleChange}
                                slotProps={{
                                    htmlInput: {
                                        min: 1
                                    }
                                }}
                            />
                        </Grid>
                        <Grid size={{ xs: 12, md: 6 }}>
                            <TextField
                                fullWidth
                                type="number"
                                label="Memory (MB)"
                                name="memory"
                                value={formData.memory}
                                onChange={handleChange}
                                slotProps={{
                                    htmlInput: {
                                        min: 128
                                    }
                                }}
                            />
                        </Grid>
                        <Grid size={{ xs: 12, md: 6 }}>
                            <TextField
                                fullWidth
                                type="number"
                                label="Virtual Cores"
                                name="vCores"
                                value={formData.vCores}
                                onChange={handleChange}
                                slotProps={{
                                    htmlInput: {
                                        min: 1
                                    }
                                }}
                            />
                        </Grid>
                        <Grid size={{ xs: 12}}>
                            <TextField
                                fullWidth
                                multiline
                                rows={4}
                                label="Commands (one per line)"
                                name="commands"
                                value={formData.commands}
                                onChange={handleChange}
                                helperText="Enter each command on a new line"
                            />
                        </Grid>
                        <Grid size={{ xs: 12}}>
                            <Button
                                type="submit"
                                variant="contained"
                                startIcon={<SendIcon />}
                                disabled={submitting}
                                size="large"
                            >
                                {submitting ? 'Submitting...' : 'Submit Application'}
                            </Button>
                        </Grid>
                    </Grid>
                </form>
            </CardContent>
        </Card>
    );
};

export default ApplicationSubmit;
