server:
  host: "0.0.0.0"
  port: 5000
  debug: true

hadoop:
  home: "/opt/hadoop"
  yarn:
    rm_url: "http://10.1.1.144:8088"

jobs:
  - name: "event_aggregation_ranking"
    id: 1
    engines:
      hadoop:
        jar_path: "/home/hadoop/github-event-aggregation-ranking/hadoop/target/hadoop-1.0-SNAPSHOT.jar"
        main_class: "it.unipi.App"
      spark:
        script: "/home/hadoop/github-event-aggregation-ranking/spark/main.py"
      python:
        script: "/home/hadoop/github-event-aggregation-ranking/python-non-parallel/main.py"

configuration:
  job:
    max_concurrent: 5
    timeout: 3600
